### ISSUE TITLE
mc2 run failed

### ISSUE THREAD

**Issue by yang8621** [mc2-project/mc2#195]
Could help with this? Thanks.

docker run --env HTTP_PROXY="XXXXXXXXXXXXX" --env HTTPS_PROXY="XXXXXXXXXXXX" -it -v ~/github/mc2-project/playground:/mc2/client/playground mc2project/mc2_img:v0.1.3

root@da42abf41b17:/mc2/client# cp -r quickstart/* playground
root@da42abf41b17:/mc2/client# mc2 configure $(pwd)/playground/config.yaml
2021-12-14 07:13:06 - INFO - Set configuration path to /mc2/client/playground/config.yaml
root@da42abf41b17:/mc2/client# mc2 init
2021-12-14 07:13:12 - WARNING - Skipping keypair generation - private key already exists at /mc2/client/playground/keys/user1.pem
2021-12-14 07:13:12 - WARNING - Skipping symmetric key generation - key already exists at /mc2/client/playground/keys/user1_sym.key
2021-12-14 07:13:12 - INFO - init finished successfully
root@da42abf41b17:/mc2/client# mc2 start
2021-12-14 07:13:15 - INFO - Running 'cd /mc2/opaque-sql; build/sbt run' locally
2021-12-14 07:13:15 - INFO - start finished successfully
root@da42abf41b17:/mc2/client# mc2 upload
2021-12-14 07:13:23 - HOST - info - Successfully initialized cryptography module.
^[[A2021-12-14 07:13:23 - INFO - Encrypted /mc2/client/playground/data/opaquesql.csv in sql format and outputted to /mc2/client/playground/data/opaquesql.csv.enc
2021-12-14 07:13:23 - INFO - Using local deployment. Copying /mc2/client/playground/data/opaquesql.csv.enc to /mc2/data/opaquesql.csv.enc
2021-12-14 07:13:23 - INFO - Using local deployment. Copying /mc2/client/playground/data/opaquesql.csv.enc to /mc2/data/opaquesql.csv.enc
2021-12-14 07:13:23 - INFO - upload finished successfully
root@da42abf41b17:/mc2/client# mc2 run
E1214 07:13:26.457284059     214 http_proxy.cc:81]           'https' scheme not supported in proxy URI
Traceback (most recent call last):
  File "/mc2/client/mc2.py", line 192, in <module>
    mc2.configure_job(config)
  File "/usr/local/lib/python3.6/dist-packages/mc2client-0.0.1-py3.6.egg/mc2client/core.py", line 1215, in configure_job
    _attest(head_address, simulation_mode, enclave_signer_pem)
  File "/usr/local/lib/python3.6/dist-packages/mc2client-0.0.1-py3.6.egg/mc2client/core.py", line 1271, in _attest
    response = stub.GetRemoteEvidence(attest_pb2.AttestationStatus(status=0))
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1639466006.457566980","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1639466006.457565708","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

**Comment by chester-leung** [comment]
@yang8621 the error you're seeing is a result of the mc2 compute service ([Opaque SQL](https://github.com/mc2-project/opaque-sql)) not being up.

Please wait a few min before running `mc2 start` and `mc2 run` for everything to start up in the background. Currently we don't have any mechanism to indicate when everything has been successfully started, but waiting a few minutes should solve this.

**Comment by yang8621** [comment]
Thanks.  But after waiting several mins, it's still failed. Seems related to the proxy?
E1216 04:21:52.442752118     236 http_proxy.cc:81]           'https' scheme not supported in proxy URI

**Comment by sakamataz** [comment]
When will this bug be fixed？I had the same problem

**Comment by chester-leung** [comment]
Hi @ztreble, we're preparing a major push with a bunch of cool new features by end of January. The quickstart will change at that point - stay tuned!
